import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ProductsArraySchema, type Product } from '@specfinder/shared';

const __dirname = dirname(fileURLToPath(import.meta.url));

const facePaperColors: Record<string, string> = {
  pink: '#D6336C',
  green: '#2F9E68',
  ivory: '#B8A88A',
  grey: '#4C5A6B',
  none: '#DFE1DE',
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function svgPlaceholder(facePaper: string, label: string): string {
  const color = facePaperColors[facePaper] ?? facePaperColors.none;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="480" height="320" viewBox="0 0 480 320"><rect width="480" height="320" fill="#FBFBFA"/><rect x="40" y="40" width="400" height="240" rx="4" fill="${color}" fill-opacity="0.15" stroke="${color}" stroke-width="2"/><text x="240" y="170" text-anchor="middle" font-family="monospace" font-size="14" fill="#16191C">${label}</text></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

function materialNumber(index: number): string {
  return String(7600000 + index).padStart(8, '0');
}

function makeVariants(
  productIndex: number,
  thicknesses: number[],
  options?: { single?: boolean; seven?: boolean },
): Product['variants'] {
  if (options?.single) {
    return [
      {
        materialNumber: materialNumber(productIndex * 10),
        widthMm: 1200,
        lengthMm: 2400,
        thicknessMm: thicknesses[0] ?? 12.5,
        weightKg: 28.8,
        weightPerSqmKg: 10.0,
        piecesPerPallet: 52,
        coverageSqm: 2.88,
      },
    ];
  }

  const count = options?.seven ? 7 : Math.min(thicknesses.length, 4);
  const selected = options?.seven
    ? [9.5, 12.5, 15, 18, 20, 25, 30]
    : thicknesses.slice(0, count);

  return selected.map((thickness, i) => ({
    materialNumber: materialNumber(productIndex * 10 + i),
    widthMm: 1200,
    lengthMm: i % 2 === 0 ? 2400 : 3000,
    thicknessMm: thickness,
    weightKg: Number((thickness * 1.9).toFixed(1)),
    weightPerSqmKg: Number((thickness * 0.8).toFixed(1)),
    piecesPerPallet: 40 + i * 4,
    coverageSqm: Number(
      ((1200 * (i % 2 === 0 ? 2400 : 3000)) / 1_000_000).toFixed(2),
    ),
  }));
}

function makeDocuments(name: string, hasEpd: boolean): Product['documents'] {
  const base = [
    {
      type: 'TDS' as const,
      title: `${name} technical datasheet`,
      fileType: 'PDF' as const,
      sizeKb: 840,
      pages: 12,
      updatedAt: '2025-11-01',
      url: '#',
    },
    {
      type: 'SDS' as const,
      title: `${name} safety datasheet`,
      fileType: 'PDF' as const,
      sizeKb: 420,
      pages: 6,
      updatedAt: '2025-10-15',
      url: '#',
    },
    {
      type: 'DoP' as const,
      title: `${name} declaration of performance`,
      fileType: 'PDF' as const,
      sizeKb: 180,
      pages: 2,
      updatedAt: '2025-09-20',
      url: '#',
    },
  ];
  if (hasEpd) {
    base.push({
      type: 'EPD',
      title: `${name} environmental product declaration`,
      fileType: 'PDF',
      sizeKb: 1200,
      pages: 18,
      updatedAt: '2025-08-01',
      url: '#',
    });
  }
  base.push(
    {
      type: 'CAD',
      title: `${name} CAD details`,
      fileType: 'PDF',
      sizeKb: 960,
      pages: null,
      updatedAt: '2025-07-01',
      url: '#',
    },
    {
      type: 'BIM',
      title: `${name} BIM object`,
      fileType: 'PDF',
      sizeKb: 640,
      pages: null,
      updatedAt: '2025-07-01',
      url: '#',
    },
  );
  return base;
}

type ProductTemplate = Omit<Product, 'id' | 'slug' | 'imageUrl'> & {
  variantOptions?: { single?: boolean; seven?: boolean };
};

function toProduct(template: ProductTemplate, index: number): Product {
  const id = `prod-${String(index + 1).padStart(3, '0')}`;
  const slug = slugify(template.name);
  return {
    ...template,
    id,
    slug,
    variants: makeVariants(
      index + 1,
      [9.5, 12.5, 15, 18, 20],
      template.variantOptions,
    ),
    imageUrl: svgPlaceholder(template.facePaper, template.name),
  };
}

const gypsumBoards: ProductTemplate[] = [
  {
    name: 'Aurelith Standard 12.5',
    tagline: 'General purpose interior board',
    description:
      'Standard gypsum board for dry interior partitions and ceilings.',
    category: 'gypsum_board',
    family: 'Standard boards',
    facePaper: 'ivory',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 33,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.25,
      maxHeightM: 3.0,
    },
    standards: ['EN 520 Type A', 'EN 13501-1'],
    sustainability: { recycledContentPct: 18, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Standard 15',
    tagline: 'Thicker standard board for improved stiffness',
    description: '15 mm standard board for high-traffic corridors.',
    category: 'gypsum_board',
    family: 'Standard boards',
    facePaper: 'ivory',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 36,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.25,
      maxHeightM: 3.3,
    },
    standards: ['EN 520 Type A'],
    sustainability: { recycledContentPct: 20, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Standard Lite',
    tagline: 'Lightweight standard board',
    description: 'Reduced weight board for manual handling on site.',
    category: 'gypsum_board',
    family: 'Standard boards',
    facePaper: 'ivory',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 31,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.24,
      maxHeightM: 2.8,
    },
    standards: ['EN 520 Type A'],
    sustainability: { recycledContentPct: 15, hasEpd: false },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Ignis 12.5',
    tagline: 'Fire-resistant, high density core',
    description: 'Pink-faced fire board for EI 60–90 partition systems.',
    category: 'gypsum_board',
    family: 'Fire-resistant boards',
    facePaper: 'pink',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 48,
      moistureClass: 'none',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.22,
      maxHeightM: 4.0,
    },
    standards: ['EN 520 Type F', 'EN 13501-1'],
    sustainability: { recycledContentPct: 22, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Ignis 15',
    tagline: 'High-density fire-rated core',
    description: '15 mm fire board for EI 90 shaft walls.',
    category: 'gypsum_board',
    family: 'Fire-resistant boards',
    facePaper: 'pink',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 90,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 54,
      moistureClass: 'none',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.21,
      maxHeightM: 4.5,
    },
    standards: ['EN 520 Type F', 'EN 13501-1'],
    sustainability: { recycledContentPct: 24, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Ignis 18',
    tagline: 'Maximum fire performance board',
    description: '18 mm board for EI 120 fire compartments.',
    category: 'gypsum_board',
    family: 'Fire-resistant boards',
    facePaper: 'pink',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 120,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 58,
      moistureClass: 'none',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.2,
      maxHeightM: 5.0,
    },
    standards: ['EN 520 Type F'],
    sustainability: { recycledContentPct: 26, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Ignis Acoustic',
    tagline: 'Fire and acoustic optimised board',
    description: 'Board tuned for high Rw with EI 60 compliance.',
    category: 'gypsum_board',
    family: 'Fire-resistant boards',
    facePaper: 'pink',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 62,
      moistureClass: 'none',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.22,
      maxHeightM: 4.2,
    },
    standards: ['EN 520 Type F'],
    sustainability: { recycledContentPct: 21, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Aqua H2',
    tagline: 'Moisture-resistant for damp areas',
    description: 'Green-faced board for bathrooms and kitchens.',
    category: 'gypsum_board',
    family: 'Moisture-resistant boards',
    facePaper: 'green',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 40,
      moistureClass: 'H2',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.24,
      maxHeightM: 3.0,
    },
    standards: ['EN 520 Type H1'],
    sustainability: { recycledContentPct: 17, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Aqua H3',
    tagline: 'Wet room rated board',
    description: 'Board for direct tile adhesion in wet rooms.',
    category: 'gypsum_board',
    family: 'Moisture-resistant boards',
    facePaper: 'green',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 42,
      moistureClass: 'H3',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.24,
      maxHeightM: 3.0,
    },
    standards: ['EN 520 Type H2'],
    sustainability: { recycledContentPct: 16, hasEpd: false },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Aqua Fire H2',
    tagline: 'Fire and moisture resistant',
    description: 'Combined fire and damp exposure board.',
    category: 'gypsum_board',
    family: 'Moisture-resistant boards',
    facePaper: 'green',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 50,
      moistureClass: 'H2',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.23,
      maxHeightM: 3.5,
    },
    standards: ['EN 520 Type F/H1'],
    sustainability: { recycledContentPct: 19, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Shield Impact',
    tagline: 'Impact-resistant partition board',
    description: 'Grey-faced board for corridors and sports halls.',
    category: 'gypsum_board',
    family: 'Impact-resistant boards',
    facePaper: 'grey',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 44,
      moistureClass: 'none',
      impactResistanceClass: 'Severe',
      thermalConductivity: 0.25,
      maxHeightM: 3.2,
    },
    standards: ['EN 520 Type I'],
    sustainability: { recycledContentPct: 20, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Shield Fire',
    tagline: 'Impact and fire rated board',
    description: 'Dual performance board for healthcare corridors.',
    category: 'gypsum_board',
    family: 'Impact-resistant boards',
    facePaper: 'grey',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 52,
      moistureClass: 'none',
      impactResistanceClass: 'Severe',
      thermalConductivity: 0.23,
      maxHeightM: 3.8,
    },
    standards: ['EN 520 Type F/I'],
    sustainability: { recycledContentPct: 23, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Ceiling Pro',
    tagline: 'Ceiling-optimised board',
    description: 'Lightweight ceiling board with square edge.',
    category: 'gypsum_board',
    family: 'Ceiling boards',
    facePaper: 'ivory',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 35,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.24,
      maxHeightM: null,
    },
    standards: ['EN 520 Type A'],
    sustainability: { recycledContentPct: 18, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Ceiling Fire',
    tagline: 'Fire-rated ceiling board',
    description: 'Fire performance ceiling board for protected zones.',
    category: 'gypsum_board',
    family: 'Ceiling boards',
    facePaper: 'pink',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 46,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.22,
      maxHeightM: null,
    },
    standards: ['EN 520 Type F'],
    sustainability: { recycledContentPct: 21, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Shaft 20',
    tagline: 'Shaft wall specialist board',
    description: '20 mm board for service shaft enclosures.',
    category: 'gypsum_board',
    family: 'Fire-resistant boards',
    facePaper: 'pink',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 90,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 56,
      moistureClass: 'none',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.2,
      maxHeightM: 6.0,
    },
    standards: ['EN 520 Type F'],
    sustainability: { recycledContentPct: 25, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
    variantOptions: { seven: true },
  },
  {
    name: 'Aurelith Acoustic 12.5',
    tagline: 'Acoustic performance board',
    description: 'Board for Rw 50+ single stud partitions.',
    category: 'gypsum_board',
    family: 'Acoustic boards',
    facePaper: 'ivory',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 55,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.24,
      maxHeightM: 3.5,
    },
    standards: ['EN 520 Type A'],
    sustainability: { recycledContentPct: 19, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Acoustic 15',
    tagline: 'High Rw acoustic board',
    description: 'Dense core board for acoustic separation walls.',
    category: 'gypsum_board',
    family: 'Acoustic boards',
    facePaper: 'ivory',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 60,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.23,
      maxHeightM: 3.8,
    },
    standards: ['EN 520 Type A'],
    sustainability: { recycledContentPct: 20, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
  {
    name: 'Aurelith Facade Sheathing',
    tagline: 'Exterior sheathing board',
    description: 'Weather-resistant sheathing for ventilated façades.',
    category: 'gypsum_board',
    family: 'Façade boards',
    facePaper: 'grey',
    applications: ['facade'],
    areaOfApplication: 'exterior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 38,
      moistureClass: 'H2',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.22,
      maxHeightM: null,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 14, hasEpd: false },
    edgeProfile: 'square',
    documents: [],
    variantOptions: { single: true },
  },
];

const cementBoards: ProductTemplate[] = [
  {
    name: 'Aurelith Cement Base 12',
    tagline: 'Cementitious base board',
    description: 'Non-combustible base board for tile backing.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'grey',
    applications: ['interior_wall', 'facade'],
    areaOfApplication: 'both',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A1',
      soundReductionRw: 45,
      moistureClass: 'H3',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.23,
      maxHeightM: 3.0,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 12, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Cement Fire 15',
    tagline: 'Fire-rated cement board',
    description: 'A1 reaction to fire cement board for fire zones.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'grey',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 90,
      reactionToFireClass: 'A1',
      soundReductionRw: 50,
      moistureClass: 'H2',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.22,
      maxHeightM: 4.0,
    },
    standards: ['EN 12467', 'EN 13501-1'],
    sustainability: { recycledContentPct: 10, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Cement Floor',
    tagline: 'Floor substrate board',
    description: 'Rigid floor board for wet area tiling.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'none',
    applications: ['floor'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A1',
      soundReductionRw: 42,
      moistureClass: 'H3',
      impactResistanceClass: 'Severe',
      thermalConductivity: 0.24,
      maxHeightM: null,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 8, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Cement Facade',
    tagline: 'Exterior cement board',
    description: 'Weatherproof façade cladding substrate.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'grey',
    applications: ['facade'],
    areaOfApplication: 'exterior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A1',
      soundReductionRw: 40,
      moistureClass: 'H3',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.21,
      maxHeightM: null,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 11, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Cement Acoustic',
    tagline: 'Acoustic cement board',
    description: 'High mass board for acoustic floors.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'grey',
    applications: ['floor', 'interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A1',
      soundReductionRw: 58,
      moistureClass: 'H2',
      impactResistanceClass: 'Hard body',
      thermalConductivity: 0.22,
      maxHeightM: null,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 9, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Cement Lite',
    tagline: 'Lightweight cement board',
    description: 'Reduced weight cement board for overhead use.',
    category: 'cement_board',
    family: 'Cement boards',
    facePaper: 'none',
    applications: ['ceiling', 'interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A1',
      soundReductionRw: 38,
      moistureClass: 'H2',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.25,
      maxHeightM: 3.0,
    },
    standards: ['EN 12467'],
    sustainability: { recycledContentPct: 7, hasEpd: true },
    edgeProfile: 'tapered',
    documents: [],
  },
];

const insulation: ProductTemplate[] = [
  {
    name: 'Aurelith Wool Partition 60',
    tagline: 'Mineral wool for partitions',
    description: 'Glass mineral wool for stud cavities.',
    category: 'insulation',
    family: 'Mineral wool',
    facePaper: 'none',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A1',
      soundReductionRw: 45,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: 0.035,
      maxHeightM: null,
    },
    standards: ['EN 13162'],
    sustainability: { recycledContentPct: 30, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Wool Acoustic 80',
    tagline: 'High-density acoustic wool',
    description: 'Dense wool for Rw improvement.',
    category: 'insulation',
    family: 'Mineral wool',
    facePaper: 'none',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 90,
      reactionToFireClass: 'A1',
      soundReductionRw: 52,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: 0.034,
      maxHeightM: null,
    },
    standards: ['EN 13162'],
    sustainability: { recycledContentPct: 35, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Wool Facade 120',
    tagline: 'Façade insulation slab',
    description: 'Non-combustible façade insulation.',
    category: 'insulation',
    family: 'Mineral wool',
    facePaper: 'none',
    applications: ['facade'],
    areaOfApplication: 'exterior',
    performance: {
      fireResistanceMin: 120,
      reactionToFireClass: 'A1',
      soundReductionRw: 35,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: 0.033,
      maxHeightM: null,
    },
    standards: ['EN 13162'],
    sustainability: { recycledContentPct: 28, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith PIR Floor 40',
    tagline: 'PIR floor insulation',
    description: 'High-compression floor insulation board.',
    category: 'insulation',
    family: 'PIR boards',
    facePaper: 'none',
    applications: ['floor'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'E',
      soundReductionRw: 30,
      moistureClass: 'H2',
      impactResistanceClass: null,
      thermalConductivity: 0.022,
      maxHeightM: null,
    },
    standards: ['EN 13165'],
    sustainability: { recycledContentPct: 5, hasEpd: true },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith EPS Facade 80',
    tagline: 'EPS façade insulation',
    description: 'Expanded polystyrene for ETICS systems.',
    category: 'insulation',
    family: 'EPS boards',
    facePaper: 'none',
    applications: ['facade'],
    areaOfApplication: 'exterior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'E',
      soundReductionRw: 28,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: 0.032,
      maxHeightM: null,
    },
    standards: ['EN 13163'],
    sustainability: { recycledContentPct: 0, hasEpd: false },
    edgeProfile: 'square',
    documents: [],
  },
  {
    name: 'Aurelith Wool Ceiling',
    tagline: 'Ceiling cavity insulation',
    description: 'Lightweight wool for suspended ceilings.',
    category: 'insulation',
    family: 'Mineral wool',
    facePaper: 'none',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A1',
      soundReductionRw: 40,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: 0.036,
      maxHeightM: null,
    },
    standards: ['EN 13162'],
    sustainability: { recycledContentPct: 32, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
];

const ceilingTiles: ProductTemplate[] = [
  {
    name: 'Aurelith Tile Standard',
    tagline: 'Standard ceiling tile',
    description: 'Mineral ceiling tile for grid systems.',
    category: 'ceiling_tile',
    family: 'Ceiling tiles',
    facePaper: 'ivory',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 35,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.04,
      maxHeightM: null,
    },
    standards: ['EN 13964'],
    sustainability: { recycledContentPct: 25, hasEpd: true },
    edgeProfile: 'recessed',
    documents: [],
  },
  {
    name: 'Aurelith Tile Acoustic',
    tagline: 'High NRC ceiling tile',
    description: 'Acoustic absorption tile for offices.',
    category: 'ceiling_tile',
    family: 'Ceiling tiles',
    facePaper: 'ivory',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 42,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.04,
      maxHeightM: null,
    },
    standards: ['EN 13964'],
    sustainability: { recycledContentPct: 28, hasEpd: true },
    edgeProfile: 'recessed',
    documents: [],
  },
  {
    name: 'Aurelith Tile Fire',
    tagline: 'Fire-rated ceiling tile',
    description: 'Fire performance tile for escape routes.',
    category: 'ceiling_tile',
    family: 'Ceiling tiles',
    facePaper: 'pink',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 60,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 38,
      moistureClass: 'none',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.04,
      maxHeightM: null,
    },
    standards: ['EN 13964'],
    sustainability: { recycledContentPct: 22, hasEpd: true },
    edgeProfile: 'recessed',
    documents: [],
  },
  {
    name: 'Aurelith Tile Moisture',
    tagline: 'Humidity-resistant tile',
    description: 'Ceiling tile for kitchens and changing rooms.',
    category: 'ceiling_tile',
    family: 'Ceiling tiles',
    facePaper: 'green',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: 36,
      moistureClass: 'H2',
      impactResistanceClass: 'Soft body',
      thermalConductivity: 0.04,
      maxHeightM: null,
    },
    standards: ['EN 13964'],
    sustainability: { recycledContentPct: 20, hasEpd: true },
    edgeProfile: 'recessed',
    documents: [],
  },
];

const profiles: ProductTemplate[] = [
  {
    name: 'Aurelith Stud C50',
    tagline: 'Standard partition stud',
    description: 'Galvanised steel C-stud for 50 mm systems.',
    category: 'profile',
    family: 'Metal profiles',
    facePaper: 'none',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A1',
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: 4.5,
    },
    standards: ['EN 14195'],
    sustainability: { recycledContentPct: 45, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Track U50',
    tagline: 'Floor and head track',
    description: 'U-track for partition framing.',
    category: 'profile',
    family: 'Metal profiles',
    facePaper: 'none',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A1',
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: null,
    },
    standards: ['EN 14195'],
    sustainability: { recycledContentPct: 45, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Ceiling Main Tee',
    tagline: 'Suspended ceiling main tee',
    description: 'Primary grid member for ceiling systems.',
    category: 'profile',
    family: 'Ceiling grid',
    facePaper: 'none',
    applications: ['ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: 'A1',
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: null,
    },
    standards: ['EN 13964'],
    sustainability: { recycledContentPct: 40, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
];

const fillersAccessories: ProductTemplate[] = [
  {
    name: 'Aurelith Joint Filler',
    tagline: 'Ready-mixed joint compound',
    description: 'Air-drying compound for tapered edges.',
    category: 'filler',
    family: 'Joint compounds',
    facePaper: 'none',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 30,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: null,
    },
    standards: ['EN 13963'],
    sustainability: { recycledContentPct: 10, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Fire Sealant',
    tagline: 'Intumescent fire sealant',
    description: 'Fire-stopping sealant for joints and penetrations.',
    category: 'accessory',
    family: 'Fire stopping',
    facePaper: 'none',
    applications: ['interior_wall'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: 120,
      reactionToFireClass: 'A2-s1,d0',
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: null,
    },
    standards: ['EN 1366-4'],
    sustainability: { recycledContentPct: 0, hasEpd: true },
    edgeProfile: 'none',
    documents: [],
  },
  {
    name: 'Aurelith Screw System',
    tagline: 'Self-drilling board screws',
    description: 'Corrosion-resistant screws for board fixing.',
    category: 'accessory',
    family: 'Fixings',
    facePaper: 'none',
    applications: ['interior_wall', 'ceiling'],
    areaOfApplication: 'interior',
    performance: {
      fireResistanceMin: null,
      reactionToFireClass: null,
      soundReductionRw: null,
      moistureClass: 'none',
      impactResistanceClass: null,
      thermalConductivity: null,
      maxHeightM: null,
    },
    standards: ['EN 14566'],
    sustainability: { recycledContentPct: 60, hasEpd: false },
    edgeProfile: 'none',
    documents: [],
  },
];

const allTemplates = [
  ...gypsumBoards,
  ...cementBoards,
  ...insulation,
  ...ceilingTiles,
  ...profiles,
  ...fillersAccessories,
];

if (allTemplates.length !== 40) {
  throw new Error(`Expected 40 products, got ${allTemplates.length}`);
}

const products: Product[] = allTemplates.map((template, index) => {
  const { variantOptions, documents: _docs, ...rest } = template;
  const product = toProduct(
    {
      ...rest,
      documents: makeDocuments(template.name, template.sustainability.hasEpd),
      variantOptions,
    },
    index,
  );
  return product;
});

const parsed = ProductsArraySchema.parse(products);

const outputPath = join(__dirname, '../data/products.seed.json');
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, JSON.stringify(parsed, null, 2));

console.log(`Generated ${parsed.length} products to ${outputPath}`);
